# Generated by Django 6.0 on 2025-12-09 08:19

import contracts.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'contracts_contract_type',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'contracts_department',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('color', models.CharField(default='#6c757d', max_length=7)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'contracts_tag',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ClausePlaybookEntry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, default='', max_length=100)),
                ('recommended_text', models.TextField()),
                ('risk_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='LOW', max_length=10)),
                ('guidance_notes', models.TextField(blank=True, default='')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'contracts_clause_playbook_entry',
                'ordering': ['category', 'label'],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contract_number', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('title', models.CharField(db_index=True, max_length=500)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('TERMINATED', 'Terminated'), ('ARCHIVED', 'Archived')], db_index=True, default='DRAFT', max_length=20)),
                ('category', models.CharField(choices=[('SALES', 'Sales'), ('PROCUREMENT', 'Procurement'), ('HR', 'Human Resources'), ('LEGAL', 'Legal'), ('FINANCE', 'Finance'), ('PARTNERSHIP', 'Partnership'), ('NDA', 'Non-Disclosure Agreement'), ('SERVICE', 'Service Agreement'), ('OTHER', 'Other')], default='OTHER', max_length=50)),
                ('sub_category', models.CharField(blank=True, default='', max_length=100)),
                ('org_entity', models.CharField(blank=True, default='', max_length=255)),
                ('region_country', models.CharField(blank=True, default='', max_length=100)),
                ('customer_or_vendor_name', models.CharField(db_index=True, max_length=500)),
                ('customer_or_vendor_address', models.TextField(blank=True, default='')),
                ('value_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('currency', models.CharField(blank=True, default='INR', max_length=8)),
                ('opportunity_id', models.CharField(blank=True, default='', max_length=100)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, db_index=True, null=True)),
                ('auto_renewal', models.BooleanField(default=False)),
                ('renewal_notice_date', models.DateField(blank=True, null=True)),
                ('assignment_status', models.CharField(choices=[('NOT_ASSIGNED', 'Not Assigned'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='NOT_ASSIGNED', max_length=20)),
                ('is_confidential', models.BooleanField(default=False)),
                ('extra_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_contracts', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_contracts', to=settings.AUTH_USER_MODEL)),
                ('contract_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='contracts.contracttype')),
                ('bu_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='contracts.department')),
            ],
            options={
                'db_table': 'contracts_contract',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Clause',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('risk_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='LOW', max_length=10)),
                ('is_from_playbook', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('playbook_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_in_clauses', to='contracts.clauseplaybookentry')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clauses', to='contracts.contract')),
            ],
            options={
                'db_table': 'contracts_clause',
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='AdditionalApproval',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20)),
                ('reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_comment', models.TextField(blank=True, default='')),
                ('due_date', models.DateField(blank=True, null=True)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals_to_review', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals_requested', to=settings.AUTH_USER_MODEL)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='contracts.contract')),
            ],
            options={
                'db_table': 'contracts_additional_approval',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractFile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=contracts.models.ContractFile.contract_file_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xlsx', 'xls', 'ppt', 'pptx', 'txt', 'jpg', 'jpeg', 'png'])])),
                ('original_filename', models.CharField(max_length=500)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('mime_type', models.CharField(blank=True, default='', max_length=100)),
                ('is_primary', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, default='')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='contracts.contract')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'contracts_contract_file',
                'ordering': ['-is_primary', '-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Deviation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('risk_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='LOW', max_length=10)),
                ('justification', models.TextField(blank=True, default='')),
                ('approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_deviations', to=settings.AUTH_USER_MODEL)),
                ('clause', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deviations', to='contracts.clause')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deviations', to='contracts.contract')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_deviations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'contracts_deviation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RiskItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='LOW', max_length=10)),
                ('mitigation', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('MITIGATED', 'Mitigated'), ('ACCEPTED', 'Accepted'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risks', to='contracts.contract')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'contracts_risk_item',
                'ordering': ['-severity', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SignatureRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('party', models.CharField(choices=[('CUSTOMER', 'Customer'), ('VENDOR', 'Vendor'), ('INTERNAL', 'Internal')], max_length=20)),
                ('signatory_name', models.CharField(max_length=255)),
                ('signatory_email', models.EmailField(max_length=254)),
                ('signatory_phone', models.CharField(blank=True, default='', max_length=20)),
                ('signatory_designation', models.CharField(blank=True, default='', max_length=255)),
                ('sign_type', models.CharField(choices=[('AADHAAR', 'Aadhaar eSign'), ('WET', 'Wet Signature'), ('ESIGN', 'Electronic Signature'), ('DSC', 'Digital Signature Certificate')], default='ESIGN', max_length=20)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('signature_reference', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='contracts.contract')),
            ],
            options={
                'db_table': 'contracts_signature_record',
                'ordering': ['party', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.contract')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.tag')),
            ],
            options={
                'db_table': 'contracts_contract_tag',
                'unique_together': {('contract', 'tag')},
            },
        ),
        migrations.AddField(
            model_name='contract',
            name='tags',
            field=models.ManyToManyField(related_name='contracts', through='contracts.ContractTag', to='contracts.tag'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('CREATE_CONTRACT', 'Contract Created'), ('UPDATE_CONTRACT', 'Contract Updated'), ('DELETE_CONTRACT', 'Contract Deleted'), ('CHANGE_STATUS', 'Status Changed'), ('ADD_FILE', 'File Added'), ('REMOVE_FILE', 'File Removed'), ('ADD_VERSION', 'Version Added'), ('CREATE_APPROVAL', 'Approval Requested'), ('APPROVE', 'Approved'), ('REJECT', 'Rejected'), ('CANCEL_APPROVAL', 'Approval Cancelled'), ('SHARE', 'Contract Shared'), ('UNSHARE', 'Share Removed'), ('ADD_CLAUSE', 'Clause Added'), ('UPDATE_CLAUSE', 'Clause Updated'), ('ADD_DEVIATION', 'Deviation Added'), ('ADD_RISK', 'Risk Added'), ('ADD_SIGNATURE', 'Signature Added'), ('SIGN', 'Document Signed'), ('VIEW', 'Contract Viewed'), ('DOWNLOAD', 'File Downloaded')], db_index=True, max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='contracts.contract')),
            ],
            options={
                'db_table': 'contracts_audit_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['contract', 'action', 'created_at'], name='contracts_a_contrac_52a69d_idx')],
            },
        ),
        migrations.CreateModel(
            name='ContractVersion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField()),
                ('label', models.CharField(max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to=contracts.models.ContractVersion.version_file_path)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='contracts.contract')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'contracts_contract_version',
                'ordering': ['-version_number'],
                'unique_together': {('contract', 'version_number')},
            },
        ),
        migrations.CreateModel(
            name='ContractShare',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('access_level', models.CharField(choices=[('VIEW', 'View Only'), ('EDIT', 'Edit')], default='VIEW', max_length=10)),
                ('shared_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='contracts.contract')),
                ('shared_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shares_created', to=settings.AUTH_USER_MODEL)),
                ('shared_with_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shared_contracts', to=settings.AUTH_USER_MODEL)),
                ('shared_with_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shared_contracts', to='contracts.department')),
            ],
            options={
                'db_table': 'contracts_contract_share',
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('shared_with_department__isnull', True), ('shared_with_user__isnull', False)), models.Q(('shared_with_department__isnull', False), ('shared_with_user__isnull', True)), _connector='OR'), name='share_user_or_department')],
            },
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['status', 'created_at'], name='contracts_c_status_efee21_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['owner', 'status'], name='contracts_c_owner_i_e4a87d_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['end_date', 'status'], name='contracts_c_end_dat_8fe405_idx'),
        ),
    ]
